=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/basic/FinancieleEenheden.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Peter Goedegebure (None) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FinancieleEenheden">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="FinancieleEenheid" type="FinancieleEenheid" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="FinancieleEenheid">
		<xs:sequence>
			<xs:element name="TeNaamStelling" type="xs:string"/>
			<xs:element name="AdresId" type="xs:integer"/>
			<xs:element name="Personen">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="PersoonId" type="xs:integer" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== goedegep/MyWorld/goedegep.finan.apptest/src/test/resources/goedegep/finan/basic/FinancieleEenheden.xml
<?xml version="1.0" encoding="UTF-8" ?>

<FinancieleEenheden xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FinancieleEenheden.xsd">
  <FinancieleEenheid>
    <TeNaamStelling>one</TeNaamStelling>
    <AdresId>_1Kl5IFRBEeK2xboPrrxLcg</AdresId>
    <Personen>
      <PersoonId>_g3YpMFRCEeK_HqJvNMtzVA</PersoonId>
      <PersoonId>_g3YpMVRCEeK_HqJvNMtzVA</PersoonId>
      <PersoonId>_g3YpMlRCEeK_HqJvNMtzVA</PersoonId>
      <PersoonId>_g3YpM1RCEeK_HqJvNMtzVA</PersoonId>
    </Personen>
  </FinancieleEenheid>
  <FinancieleEenheid>
    <TeNaamStelling>Het gezin</TeNaamStelling>
    <AdresId>_1Kl5IVRBEeK2xboPrrxLcg</AdresId>
    <Personen>
      <PersoonId>_g3YpNVRCEeK_HqJvNMtzVA</PersoonId>
      <PersoonId>_g3YpNFRCEeK_HqJvNMtzVA</PersoonId>
      <PersoonId>_g3YpM1RCEeK_HqJvNMtzVA</PersoonId>
    </Personen>
  </FinancieleEenheid>
  <FinancieleEenheid>
    <TeNaamStelling>The company</TeNaamStelling>
    <AdresId>_1Kl5IVRBEeK2xboPrrxLcg</AdresId>
    <Personen>
      <PersoonId>_g3YpMFRCEeK_HqJvNMtzVA</PersoonId>
      <PersoonId>_g3YpNVRCEeK_HqJvNMtzVA</PersoonId>
    </Personen>
  </FinancieleEenheid>
</FinancieleEenheden>

=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/basic/FinancieleEenheden.xml
<?xml version="1.0" encoding="UTF-8"?>

<FinancieleEenheden xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FinancieleEenheden.xsd">
  <FinancieleEenheid>
    <TeNaamStelling>familie Goedegebure</TeNaamStelling>
    <AdresId>1</AdresId>
    <Personen>
      <PersoonId>1</PersoonId>
      <PersoonId>2</PersoonId>
      <PersoonId>3</PersoonId>
      <PersoonId>4</PersoonId>
    </Personen>
  </FinancieleEenheid>
</FinancieleEenheden>
