=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/BelastingKoersen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Peter Goedegebure (None) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="BelastingKoersen">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="KoersenPerKwartaal" type="KoersenPerKwartaal" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="KoersenPerKwartaal">
		<xs:sequence>
			<xs:element name="Jaar" type="xs:gYear"/>
			<xs:element name="Kwartaal" type="xs:int">
				<xs:annotation>
					<xs:documentation>Kwartaal 0 geeft begin van het jaar aan.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Koersen">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="AandeelKoersInfo" type="AandeelKoersInfo" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="StockDividendKoersInfo" type="StockDividendKoersInfo" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="OptieKoersInfo" type="OptieKoersInfo" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AandeelKoersInfo">
		<xs:sequence>
			<xs:element name="Aandeel" type="xs:string"/>
			<xs:element name="Koers" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StockDividendKoersInfo">
		<xs:sequence>
			<xs:element name="Aandeel" type="xs:string"/>
			<xs:element name="DividendReferentie" type="xs:string"/>
			<xs:element name="Koers" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OptieKoersInfo">
		<xs:sequence>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="CALL"/>
						<xs:enumeration value="PUT"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FondsNaam" type="xs:string"/>
			<xs:element name="Maand">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Jaar" type="xs:int"/>
			<xs:element name="UitoefeningsKoers" type="xs:string"/>
			<xs:element name="Koers" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== goedegep/MyWorld/goedegep.finan.apptest/src/test/resources/goedegep/finan/stocks/BelastingKoersen.xml
<?xml version="1.0" encoding="UTF-8" ?>

<BelastingKoersen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BelastingKoersen.xsd">
  <KoersenPerKwartaal>
    <Jaar>2000</Jaar><Kwartaal>2</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>AHOLD KON NLG0.50</Aandeel><Koers>e30,83</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2000</Jaar><Kwartaal>3</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING NLG1.25</Aandeel><Koers>e26,40</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>AHOLD KON NLG0.50</Aandeel><Koers>e32,13</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e24,68</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS NLG10</Aandeel><Koers>e87,90</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK WERELDMERKENFDS NLG10</Aandeel><Koers>e38,50</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2000</Jaar><Kwartaal>4</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING NLG1.25</Aandeel><Koers>e24,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>AHOLD KON EUR0.25</Aandeel><Koers>e34,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e21,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e12,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e37,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS EUR5 -1-</Aandeel><Koers>e77,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK MULTIMEDIAFONDS EUR0.8</Aandeel><Koers>e12,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBK WERELDMERKENFD EUR0.8</Aandeel><Koers>e34,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>TISCALI ITL10 (nl)</Aandeel><Koers>e16,00</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2001</Jaar><Kwartaal>1</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING NLG1.25</Aandeel><Koers>e20,73</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e25,20</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e11,06</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>NUTRECO HOLDING EUR0.24</Aandeel><Koers>e47,50</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e31,10</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS EUR5 -1-</Aandeel><Koers>e71,10</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK MULTIMEDIAFONDS EUR0.8</Aandeel><Koers>e11,05</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBK WERELDMERKENFD EUR0.8</Aandeel><Koers>e32,50</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>TISCALI ITL10 (nl)</Aandeel><Koers>e15,00</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2001</Jaar><Kwartaal>2</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING EUR0.56</Aandeel><Koers>e22,19</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e26,49</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e6,70</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>NUTRECO HOLDING EUR0.24</Aandeel><Koers>e50,60</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e31,31</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS EUR5 -1-</Aandeel><Koers>e75,75</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK MULTIMEDIAFONDS EUR0.8</Aandeel><Koers>e12,55</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBK WERELDMERKENFD EUR0.8</Aandeel><Koers>e35,50</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>TISCALI ITL10 (nl)</Aandeel><Koers>e10,20</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2001</Jaar><Kwartaal>4</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING EUR0.56</Aandeel><Koers>e18,09</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e19,52</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e5,71</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>NUTRECO HOLDING EUR0.24</Aandeel><Koers>e35,90</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e33,38</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS EUR5 -1-</Aandeel><Koers>e66,25</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK MULTIMEDIAFONDS EUR0.8</Aandeel><Koers>e10,13</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBK WERELDMERKENFD EUR0.8</Aandeel><Koers>e32,20</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>TISCALI EUR0.50</Aandeel><Koers>e10,00</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2002</Jaar><Kwartaal>1</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING EUR0.56</Aandeel><Koers>e21,77</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e28,90</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e5,87</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>NUTRECO HOLDING EUR0.24</Aandeel><Koers>e37,45</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e34,97</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS EUR5 -1-</Aandeel><Koers>e67,35</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK MULTIMEDIAFONDS EUR0.8</Aandeel><Koers>e9,15</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBK WERELDMERKENFD EUR0.8</Aandeel><Koers>e32,90</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>TISCALI EUR0.50</Aandeel><Koers>e9,71</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2002</Jaar><Kwartaal>3</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING EUR0.56</Aandeel><Koers>e11,08</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>AHOLD KON EUR0.25</Aandeel><Koers>e11,99</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e6,22</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e5,25</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>NUTRECO HOLDING EUR0.24</Aandeel><Koers>e14,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e14,70</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS EUR5 -1-</Aandeel><Koers>e43,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK MULTIMEDIAFONDS EUR0.8</Aandeel><Koers>e5,05</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBK WERELDMERKENFD EUR0.8</Aandeel><Koers>e23,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>TISCALI EUR0.50</Aandeel><Koers>e3,92</Koers></AandeelKoersInfo>
      <StockDividendKoersInfo><Aandeel>AHOLD KON EUR0.25</Aandeel><DividendReferentie>DIV02</DividendReferentie><Koers>e0,22</Koers></StockDividendKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2002</Jaar><Kwartaal>4</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING EUR0.56</Aandeel><Koers>e15,58</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>AHOLD KON EUR0.25</Aandeel><Koers>e12,10</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e7,96</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e6,20</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>NUTRECO HOLDING EUR0.24</Aandeel><Koers>e17,79</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e16,70</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK AANDELENFONDS EUR5 -1-</Aandeel><Koers>e42,90</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBANK MULTIMEDIAFONDS EUR0.8</Aandeel><Koers>e5,02</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>POSTBK WERELDMERKENFD EUR0.8</Aandeel><Koers>e23,00</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>TISCALI EUR0.50</Aandeel><Koers>e4,10</Koers></AandeelKoersInfo>
    </Koersen>
  </KoersenPerKwartaal>
  <KoersenPerKwartaal>
    <Jaar>2003</Jaar><Kwartaal>1</Kwartaal>
    <Koersen>
      <AandeelKoersInfo><Aandeel>ABN AMRO HOLDING EUR0.56</Aandeel><Koers>e13,40</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>AHOLD KON EUR0.25</Aandeel><Koers>e3,05</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>ASM LITHOGRAPHY EUR0.02</Aandeel><Koers>e5,95</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>KON KPN EUR0.24</Aandeel><Koers>e5,88</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>NUTRECO HOLDING EUR0.24</Aandeel><Koers>e14,13</Koers></AandeelKoersInfo>
      <AandeelKoersInfo><Aandeel>PHILIPS ELECTRONICS KON EUR0.20</Aandeel><Koers>e14,39</Koers></AandeelKoersInfo>
