=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/ClaimEmissions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Peter Goedegebure (None) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ClaimEmissions">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ClaimEmission" type="ClaimEmission" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ClaimEmission">
		<xs:sequence>
			<xs:element name="ShareName" type="xs:string"/>
			<xs:element name="ClaimId" type="xs:string"/>
			<xs:element name="FromAmount" type="xs:int"/>
			<xs:element name="ToAmount" type="xs:int"/>
			<xs:element name="PricePerShare" type="xs:string"/>
			<xs:element name="RightRate" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== goedegep/MyWorld/goedegep.finan.app/src/test/resources/goedegep/finan/stocks/ClaimEmissions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<ClaimEmissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ClaimEmissions.xsd">
  <ClaimEmission>
    <ShareName>AHOLD KON EUR0.25</ShareName><ClaimId>10-12-2003</ClaimId>
    <FromAmount>3</FromAmount><ToAmount>2</ToAmount>
    <PricePerShare>e4,83</PricePerShare><RightRate>e0,63</RightRate>
  </ClaimEmission>
</ClaimEmissions>

=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/ClaimEmissions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<ClaimEmissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ClaimEmissions.xsd">
  <ClaimEmission>
    <ShareName>AHOLD KON EUR0.25</ShareName><ClaimId>10-12-2003</ClaimId>
    <FromAmount>3</FromAmount><ToAmount>2</ToAmount>
    <PricePerShare>e4,83</PricePerShare><RightRate>e0,63</RightRate>
  </ClaimEmission>
  <ClaimEmission>
    <ShareName>GETRONICS EUR0.04</ShareName><ClaimId>29-04-2005</ClaimId>
    <FromAmount>3</FromAmount><ToAmount>2</ToAmount>
    <PricePerShare>e1,19</PricePerShare><RightRate>e0,08</RightRate>
  </ClaimEmission>
  <ClaimEmission>
    <ShareName>HAGEMEYER EUR1.20</ShareName><ClaimId>04-02-2004</ClaimId>
    <FromAmount>2</FromAmount><ToAmount>7</ToAmount>
    <PricePerShare>e1,20</PricePerShare><RightRate>e1,54</RightRate>
  </ClaimEmission>
  <ClaimEmission>
    <ShareName>LOGICACMG GBP0.1 -NL-</ShareName><ClaimId>07-11-2005</ClaimId>
    <FromAmount>2</FromAmount><ToAmount>1</ToAmount>
    <PricePerShare>e1,55863</PricePerShare>
  </ClaimEmission>
  <ClaimEmission>
    <ShareName>TISCALI EUR0.50</ShareName><ClaimId>01-02-2008</ClaimId>
    <FromAmount>17</FromAmount><ToAmount>6</ToAmount>
    <PricePerShare>e1,00</PricePerShare>
  </ClaimEmission>
</ClaimEmissions>
