=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/Companies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Peter Goedegebure (None) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Companies">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Company" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== goedegep/MyWorld/goedegep.finan.apptest/src/test/resources/goedegep/finan/stocks/Companies.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Companies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Companies.xsd">
  <Company>ABN AMRO Holding</Company>
  <Company>ASML Holding</Company>
  <Company>Heijmans</Company>
  <Company>Heineken</Company>
  <Company>Kon. Ahold</Company>
  <Company>Kon. DSM</Company>
  <Company>Kon. KPN</Company>
  <Company>Kon. Philips Electronics</Company>
  <Company>LogicaCMG</Company>
  <Company>Nutreco</Company>
  <Company>Postbank</Company>
  <Company>Simac</Company>
  <Company>Tiscali</Company>
  <Company>TomTom</Company>
</Companies>

=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/Companies.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Companies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Companies.xsd">
  <Company>ABN AMRO Holding</Company>
  <Company>ASML Holding</Company>
  <Company>Corporate Express</Company>
  <Company>Getronics</Company>
  <Company>Hagemeyer</Company>
  <Company>Heijmans</Company>
  <Company>Heineken</Company>
  <Company>Kon. Ahold</Company>
  <Company>Kon. DSM</Company>
  <Company>Kon. KPN</Company>
  <Company>Kon. Philips Electronics</Company>
  <Company>Libertel</Company>
  <Company>LogicaCMG</Company>
  <Company>Numico</Company>
  <Company>Nutreco</Company>
  <Company>Postbank</Company>
  <Company>Simac</Company>
  <Company>Tele Atlas</Company>
  <Company>Tiscali</Company>
  <Company>TomTom</Company>
  <Company>UPC</Company>
  <Company>Vodafone</Company>
  <Company>World Online</Company>
</Companies>
