=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/FundShares.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Peter Goedegebure (None) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FundShares">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="FundShareList" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="FundShareList">
		<xs:sequence>
			<xs:element name="FundName" type="xs:string"/>
			<xs:element name="Share" type="Share" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Share">
		<xs:sequence>
			<xs:element name="ShareName" type="xs:string"/>
			<xs:element name="RedenominationFrom" type="RedenominationFrom" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RedenominationFrom">
		<xs:sequence>
			<xs:element name="ShareName" type="xs:string"/>
			<xs:element name="FromAmount" type="xs:int"/>
			<xs:element name="ToAmount" type="xs:int"/>
			<xs:element name="Koers" type="xs:string" minOccurs="0"/>
			<xs:element name="TerugBetaling" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/FundShares.xml
<?xml version="1.0" encoding="UTF-8" ?>

<FundShares xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FundShares.xsd">
  <FundShareList>
    <FundName>ABN AMRO Holding</FundName>
    <Share><ShareName>ABN AMRO HOLDING NLG1.25</ShareName></Share>
    <Share><ShareName>ABN AMRO HOLDING EUR0.56</ShareName><RedenominationFrom><ShareName>ABN AMRO HOLDING NLG1.25</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>ASML Holding</FundName>
    <Share><ShareName>ASM LITHOGRAPHY EUR0.02</ShareName></Share>
    <Share><ShareName>ASML HOLDING EUR0.09</ShareName><RedenominationFrom><ShareName>ASM LITHOGRAPHY EUR0.02</ShareName><FromAmount>9</FromAmount><ToAmount>8</ToAmount><Koers>e23,25</Koers><TerugBetaling>e2,04</TerugBetaling></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Corporate Express</FundName>
    <Share><ShareName>CORP EXPRESS EUR1.2</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Getronics</FundName>
    <Share><ShareName>GETRONICS EUR0.04</ShareName></Share>
    <Share><ShareName>GETRONICS EUR0.28</ShareName><RedenominationFrom><ShareName>GETRONICS EUR0.04</ShareName><FromAmount>7</FromAmount><ToAmount>1</ToAmount><Koers>e8,89</Koers></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Hagemeyer</FundName>
    <Share><ShareName>HAGEMEYER NLG2.50</ShareName></Share>
    <Share><ShareName>HAGEMEYER EUR1.20</ShareName><RedenominationFrom><ShareName>HAGEMEYER NLG2.50</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Heijmans</FundName>
    <Share><ShareName>HEIJMANS EUR0.03</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Heineken</FundName>
    <Share><ShareName>HEINEKEN EUR2</ShareName></Share>
    <Share><ShareName>HEINEKEN EUR1.6</ShareName><RedenominationFrom><ShareName>HEINEKEN EUR2</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Kon. Ahold</FundName>
    <Share><ShareName>AHOLD KON NLG0.50</ShareName></Share>
    <Share><ShareName>AHOLD KON EUR0.25</ShareName><RedenominationFrom><ShareName>AHOLD KON NLG0.50</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
    <Share><ShareName>AHOLD KON EUR0.30</ShareName><RedenominationFrom><ShareName>AHOLD KON EUR0.25</ShareName><FromAmount>5</FromAmount><ToAmount>4</ToAmount><Koers>e9,47</Koers><TerugBetaling>e1,89</TerugBetaling></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Kon. DSM</FundName>
    <Share><ShareName>KON DSM EUR1.5</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Kon. KPN</FundName>
    <Share><ShareName>KON KPN EUR0.24</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Kon. Philips Electronics</FundName>
    <Share><ShareName>PHILIPS ELECTRONICS KON EUR0.20</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Libertel</FundName>
    <Share><ShareName>LIBERTEL NLG0.64</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>LogicaCMG</FundName>
    <Share><ShareName>LOGICACMG GBP0.1 -NL-</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Numico</FundName>
    <Share><ShareName>KON NUMICO EUR0.25</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Nutreco</FundName>
    <Share><ShareName>NUTRECO HOLDING EUR0.24</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Postbank Aandelenfonds</FundName>
    <Share><ShareName>POSTBANK AANDELENFONDS NLG10</ShareName></Share>
    <Share><ShareName>POSTBANK AANDELENFONDS EUR5 -1-</ShareName><RedenominationFrom><ShareName>POSTBANK AANDELENFONDS NLG10</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Postbank Beleggingsfonds</FundName>
    <Share><ShareName>Postbank Beleggingsfonds</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Postbank Financiele Wereldfonds</FundName>
    <Share><ShareName>Postbank Financiele Wereldfonds</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Postbank Multimediafonds</FundName>
    <Share><ShareName>POSTBANK MULTIMEDIAFONDS EUR5</ShareName></Share>
    <Share><ShareName>POSTBANK MULTIMEDIAFONDS EUR0.8</ShareName><RedenominationFrom><ShareName>POSTBANK MULTIMEDIAFONDS EUR5</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Postbank WereldMerkenfonds</FundName>
    <Share><ShareName>POSTBANK WERELDMERKENFDS NLG10</ShareName></Share>
    <Share><ShareName>POSTBK WERELDMERKENFD EUR0.8</ShareName><RedenominationFrom><ShareName>POSTBANK WERELDMERKENFDS NLG10</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Simac Techniek</FundName>
    <Share><ShareName>SIMAC TECHNIEK EUR0,10</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Tele Atlas</FundName>
    <Share><ShareName>TELE ATLAS EUR0.1 -NL-</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Tiscali</FundName>
    <Share><ShareName>TISCALI ITL10 (nl)</ShareName></Share>
    <Share><ShareName>TISCALI EUR0.50</ShareName><RedenominationFrom><ShareName>TISCALI ITL10 (nl)</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>TomTom</FundName>
    <Share><ShareName>TOMTOM EUR.2</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>UPC</FundName>
    <Share><ShareName>UNITED PAN-EUR COM -A- EUR1</ShareName></Share>
    <Share><ShareName>UPC EUR0.02 -A-</ShareName><RedenominationFrom><ShareName>UNITED PAN-EUR COM -A- EUR1</ShareName><FromAmount>1</FromAmount><ToAmount>1</ToAmount></RedenominationFrom></Share>
  </FundShareList>
  <FundShareList>
    <FundName>Vodafone Libertel</FundName>
    <Share><ShareName>VODAFONE LIBERTEL EUR0.3</ShareName></Share>
  </FundShareList>
  <FundShareList>
    <FundName>World Online</FundName>
    <Share><ShareName>WORLD ONLINE INTL EUR0.4</ShareName></Share>
  </FundShareList>
</FundShares>
