=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/OptionSeries.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="OptionSerie">
		<xs:sequence>
			<xs:element name="Type" type="xs:string"/>
			<xs:element name="FondsNaam" type="xs:string"/>
			<xs:element name="Maand">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Jaar" type="xs:int"/>
			<xs:element name="UitoefeningsKoers" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="OptionSeries">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="OptionSerie" type="OptionSerie" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/OptionSeries.xml
<?xml version="1.0" encoding="UTF-8" ?>

<OptionSeries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OptionSeries.xsd">
    <OptionSerie><Type>CALL</Type><FondsNaam>ASM LITHOGRAPHY EUR0.02</FondsNaam><Maand>7</Maand><Jaar>2002</Jaar><UitoefeningsKoers>e22,00</UitoefeningsKoers></OptionSerie>
    <OptionSerie><Type>CALL</Type><FondsNaam>ASM LITHOGRAPHY EUR0.02</FondsNaam><Maand>7</Maand><Jaar>2004</Jaar><UitoefeningsKoers>e14,00</UitoefeningsKoers></OptionSerie>
    <OptionSerie><Type>CALL</Type><FondsNaam>PHILIPS ELECTRONICS KON EUR0.20</FondsNaam><Maand>5</Maand><Jaar>2007</Jaar><UitoefeningsKoers>e32,00</UitoefeningsKoers></OptionSerie>
    <OptionSerie><Type>CALL</Type><FondsNaam>ASM LITHOGRAPHY EUR0.02</FondsNaam><Maand>6</Maand><Jaar>2007</Jaar><UitoefeningsKoers>e22,00</UitoefeningsKoers></OptionSerie>
    <OptionSerie><Type>PUT</Type><FondsNaam>TOMTOM EUR.2</FondsNaam><Maand>11</Maand><Jaar>2007</Jaar><UitoefeningsKoers>e60,00</UitoefeningsKoers></OptionSerie>
    <OptionSerie><Type>CALL</Type><FondsNaam>TOMTOM EUR.2</FondsNaam><Maand>1</Maand><Jaar>2008</Jaar><UitoefeningsKoers>e54,00</UitoefeningsKoers></OptionSerie>
    <OptionSerie><Type>CALL</Type><FondsNaam>TOMTOM EUR.2</FondsNaam><Maand>2</Maand><Jaar>2008</Jaar><UitoefeningsKoers>e46,00</UitoefeningsKoers></OptionSerie>
</OptionSeries>
