=== goedegep/MyWorld/goedegep.finan.app/src/main/resources/goedegep/finan/stocks/ShareDividends.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Peter Goedegebure (None) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ShareDividends">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ShareDividendsList" type="ShareDividendsList" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Dividend">
		<xs:sequence>
			<xs:element name="DividendName" type="xs:string" minOccurs="0"/>
			<xs:element name="DividendYear" type="xs:int" minOccurs="0"/>
			<xs:element name="DividendType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Contant"/>
						<xs:enumeration value="ContantOfStock"/>
						<xs:enumeration value="Drip"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DividendAmount" type="xs:string" minOccurs="0"/>
			<xs:element name="StockDividend" type="StockDividend" minOccurs="0"/>
			<xs:element name="Drip" type="Drip" minOccurs="0"/>
			<xs:element name="BelastingPercentage" type="xs:int" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StockDividend">
		<xs:sequence>
			<xs:element name="FromAmount" type="xs:int" minOccurs="0"/>
			<xs:element name="ToAmount" type="xs:int" minOccurs="0"/>
			<xs:element name="Koers" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ShareDividendsList">
		<xs:sequence>
			<xs:element name="ShareName" type="xs:string"/>
			<xs:element name="Dividend" type="Dividend" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Drip">
		<xs:sequence>
			<xs:element name="FromAmount" type="xs:string"/>
			<xs:element name="PricePerShare" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== goedegep/MyWorld/goedegep.finan.apptest/src/test/resources/goedegep/finan/stocks/ShareDividends.xml
<?xml version="1.0" encoding="UTF-8" ?>

<ShareDividends xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ShareDividends.xsd">
  <ShareDividendsList>
    <ShareName>ABN AMRO HOLDING EUR0.56</ShareName>
    <Dividend><DividendName>DIV01 -INTERIM-</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>43</FromAmount><ToAmount>1</ToAmount><Koers>e0,43465</Koers></StockDividend></Dividend>
    <Dividend><DividendName>DIV02</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,45400</Koers></StockDividend></Dividend>
    <Dividend><DividendName>INTERIM DIV02</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,44861</Koers></StockDividend></Dividend>
    <Dividend><DividendName>-DIV03-</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,4560</Koers></StockDividend></Dividend>
    <Dividend><DividendName>INTDIV03</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>36</FromAmount><ToAmount>1</ToAmount><Koers>e0,4544</Koers></StockDividend></Dividend>
    <Dividend><DividendName>DIV04</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>33</FromAmount><ToAmount>1</ToAmount><Koers>e0,515</Koers></StockDividend></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>ABN AMRO HOLDING NLG1.25</ShareName>
    <Dividend><DividendName>DIV01</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,49022</Koers></StockDividend></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>AHOLD KON EUR0.25</ShareName>
    <Dividend><DividendName>DIV02</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>100</FromAmount><ToAmount>1</ToAmount><Koers>e0,12500</Koers></StockDividend></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>AHOLD KON NLG0.50</ShareName>
    <Dividend><DividendName>INTERIM2000</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>100</FromAmount><ToAmount>1</ToAmount><Koers>e0,00</Koers></StockDividend></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>ASM LITHOGRAPHY EUR0.02</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>HEIJMANS EUR0.03</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>HEINEKEN EUR1.6</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>HEINEKEN EUR2</ShareName>
    <Dividend><DividendYear>2004</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,24</DividendAmount></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>KON DSM EUR1.5</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>KON KPN EUR0.24</ShareName>
    <Dividend><DividendName>INTERIM2000</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>143</FromAmount><ToAmount>1</ToAmount><Koers>e0,18</Koers></StockDividend></Dividend>
    <Dividend><DividendName>DIV01</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><Koers>e0,28225</Koers></StockDividend></Dividend>
    <Dividend><DividendYear>2003</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,25</DividendAmount></Dividend>
    <Dividend><DividendName>2</DividendName><DividendYear>2003</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,08</DividendAmount></Dividend>
    <Dividend><DividendYear>2004</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,27</DividendAmount></Dividend>
    <Dividend><DividendName>1</DividendName><DividendYear>2005</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,13</DividendAmount></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>LOGICACMG GBP0.1 -NL-</ShareName>
    <Dividend><DividendName>19-05-2004</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,05663</DividendAmount><BelastingPercentage>10</BelastingPercentage></Dividend>
    <Dividend><DividendName>1</DividendName><DividendYear>2004</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,03</DividendAmount></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>NUTRECO HOLDING EUR0.24</ShareName>
    <Dividend><DividendName>DIV01</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,57446</Koers></StockDividend></Dividend>
    <Dividend><DividendName>DIV02</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,53116</Koers></StockDividend></Dividend>
    <Dividend><DividendName>DIV02-2</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,28272</Koers></StockDividend></Dividend>
    <Dividend><DividendName>DIV03</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>0</FromAmount><ToAmount>1</ToAmount><Koers>e0,3767</Koers></StockDividend></Dividend>
    <Dividend><DividendName>DIV03 1/149E</DividendName><DividendType>ContantOfStock</DividendType><StockDividend><FromAmount>149</FromAmount><ToAmount>1</ToAmount><Koers>e0,1157</Koers></StockDividend></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>PHILIPS ELECTRONICS KON EUR0.20</ShareName>
    <Dividend><DividendName>DIV00</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,36</DividendAmount></Dividend>
    <Dividend><DividendName>DIV01</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,36</DividendAmount></Dividend>
    <Dividend><DividendName>DIV02</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,36</DividendAmount></Dividend>
    <Dividend><DividendName>DIV03</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,36</DividendAmount></Dividend>
    <Dividend><DividendYear>2004</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,40</DividendAmount></Dividend>
    <Dividend><DividendYear>2005</DividendYear><DividendType>Contant</DividendType><DividendAmount>e0,44</DividendAmount></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>POSTBANK AANDELENFONDS EUR5 -1-</ShareName>
    <Dividend><DividendName>DIV01</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,75</DividendAmount></Dividend>
    <Dividend><DividendName>DIV02</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,40</DividendAmount></Dividend>
    <Dividend><DividendName>DIV03</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,75</DividendAmount></Dividend>
    <Dividend><DividendName>DIV04</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,46</DividendAmount></Dividend>
    <Dividend><DividendName>DIV05</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,61</DividendAmount></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>POSTBANK AANDELENFONDS NLG10</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>POSTBANK MULTIMEDIAFONDS EUR0.8</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>POSTBANK MULTIMEDIAFONDS EUR5</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>POSTBANK WERELDMERKENFDS NLG10</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>POSTBK WERELDMERKENFD EUR0.8</ShareName>
    <Dividend><DividendName>DIV01</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,25</DividendAmount></Dividend>
    <Dividend><DividendName>DIV03</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,10</DividendAmount></Dividend>
    <Dividend><DividendName>DIV04</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,05</DividendAmount></Dividend>
    <Dividend><DividendName>DIV05</DividendName><DividendType>Contant</DividendType><DividendAmount>e0,27</DividendAmount></Dividend>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>Postbank Beleggingsfonds</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>Postbank Financiele Wereldfonds</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>SIMAC TECHNIEK EUR0,10</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>TISCALI EUR0.50</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>TISCALI ITL10 (nl)</ShareName>
  </ShareDividendsList>
  <ShareDividendsList>
    <ShareName>TOMTOM EUR.2</ShareName>
  </ShareDividendsList>
</ShareDividends>
